  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: fornecedor
    username: fornecedor
    url: jdbc:mysql://localhost:3306/fornecedor
    
